services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - api-ffmpeg  # Shared network for communication

networks:
  api-ffmpeg:
    external: true  # Use an existing network