services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - ffmpeg  # Reference the existing service name
    networks:
      - api-ffmpeg

networks:
  api-ffmpeg:
    external: true  # Use the existing network
