services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - ffmpeg  # Updated to match the service name defined below
    networks:
      - api-ffmpeg

  ffmpeg:  # Ensure this matches the `depends_on` reference
    image: ffmpeg-image
    container_name: ffmpeg-docker
    stdin_open: true
    tty: true
    networks:
      - api-ffmpeg

networks:
  api-ffmpeg:
    driver: bridge
