version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - ffmpeg  # Se asegura que el servicio ffmpeg esté disponible
    networks:
      - app_network

  ffmpeg:
    image: ffmpeg-image
    container_name: ffmpeg-docker
    stdin_open: true
    tty: true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
