# Usa la imagen base de Ubuntu
FROM ubuntu:latest

# Instalar FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Configuración predeterminada (no es necesario cambiar)
CMD ["ffmpeg", "-version"]
